Introduction to Python for Data Science
====
0. [Overview](#overview)
1. [Review](#review)
2. [Iris Data](#iris)
3. [Dictionary, list](#dict)
4. [List comprehension](#compr)
5. [Review Problems](#hmwk)

# WHOAREWE?

<ul>
<li>Ilan, Ai, Squarespace, Duke
<li>TAs: Paul and Nick, Ai
</ul>

# WHOAREYOU?

<ul>
<li>Names
<li>Programming experience
<li>Why are you here
<li>Favoriate band | restaurant (in Durham) | hometown (if not Durham)
</ul>

# COURSE OVERVIEW <a id='overview'></a>

<ul>
<li>Will be using notebooks to review concepts
<ul>
<li>Ask questions
<li>**Don't worry about memorizing or understanding everything the first time** - takes a while to sink in
<li>Do the in class exercises - collaborate!
</ul>
<li>Try the at home exercises - don't be discouraged if they take a while or you don't get it right away
<ul>
<li>Feel free to email me with questions
<li>If you want more - let me know and I'll provide more!
</ul>
<li>Syllabus is tentative - based on class flow
</ul>

### Jupyter

<ul>
<li>Interative notebook
<ul>
<li>Write code in cells and run to see output. Cells communicate - values are carried forward.
<li>Can also insert markdown or $\LaTeX$, i.e. $y = \beta_0 + \beta_1 x + \beta_2x^2$
<li>Can also insert images, etc..
</ul>
<li>Makes for easy prototyping
<li>Quick visualizations
<li>Shareable, live code
<li><a href="https://ipython.org/">IPython</a> is the Python *kernel* for Jupyter - but there is a Ruby kernel, Julia, ...
<li>...but can promote bad code practice, not used for production
<li>Spend time getting to know the notebook. Shortcuts, etc...
</ul>

Review pre work <a id='review'></a>
======

<ul>
<li>Variables
<li>Boolean logic
<li>Operators
<li>`if` statement
<li>Built-in functions
</ul>

**Q1**.
<br>

Without using Python, what's the following output?

<ol>
<li>`not (1 == 1 and 0 != 1)`
<li>`3 == 3 and (not ("testing" == "testing" or "Python" == "Fun"))`
<li>`20 == ((20 % 3) ** 2 + 1) * (9//2)`
</ol>


**Q2**.
<br>

For the following string, replace every occurrence of the first character with #, except for the first character. So:

`'this is a sentence that starts with the letter t'`

Becomes

`'this is a sen#ence #ha# s#ar#s wi#h #he le##er #'`


**Q3**.

Write a program that prints, to the console, a list of 2 integers and 1 string. Do this:

<ol>
<li>Using the `format` function
<li>Not using `format`
</ol>

For example:

`[2,'s',4]`

Each of the three elements should be a variable, not hardcoded. Make sure the spacing is as shown above.

**Q4**.
<br>

Write a function `power_floor(a,b)` that returns the floor of `a` to the power of `b`. "Floor" means "rounded down". i.e. `power_floor(5.5,3)` outputs `166`. 

# IRIS DATASET<a id='iris'></a>

In [5]:
from sklearn import datasets

In [6]:
iris = datasets.load_iris()
iris

{'DESCR': 'Iris Plants Database\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n

## How can we see the data?

In [7]:
iris.keys()

['target_names', 'data', 'target', 'DESCR', 'feature_names']

In [8]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
iris.data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [10]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

## What is this object?

Dictionary<a id='dict'></a>
----
<ul>
<li>Consist of pairs of keys and their corresponding values. Like a dictionary, lookup the `key` to get some `value`
<li>Values aren't numbered or in any specific order. Key's are also not ordered.
<li>You can add, remove, and modify the values in dictionaries
<li>Looks like a `JSON` object
</ul>

In [11]:
dictionary = {'a': 1, 'b':2, 'c':3}
dictionary

{'a': 1, 'b': 2, 'c': 3}

In [12]:
dictionary['b']

2

In [13]:
dictionary1 = dict(d = 4, e = 5, f = 6)
dictionary1

{'d': 4, 'e': 5, 'f': 6}

In [14]:
dictionary2 = dict([('a',1),('b',2),('d',3)])
dictionary2

{'a': 1, 'b': 2, 'd': 3}

In [15]:
dictionary.update(dictionary1)
dictionary

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}

In [16]:
dictionary.keys()

['a', 'c', 'b', 'e', 'd', 'f']

In [17]:
dictionary.values()

[1, 3, 2, 5, 4, 6]

In [18]:
dictionary['g'] = 7
dictionary

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7}

In [19]:
for key in dictionary:
    print key, dictionary[key]

a 1
c 3
b 2
e 5
d 4
g 7
f 6


In [20]:
for key, value in dictionary.items():
    print key, value

a 1
c 3
b 2
e 5
d 4
g 7
f 6


In [21]:
dictionary.items()

[('a', 1), ('c', 3), ('b', 2), ('e', 5), ('d', 4), ('g', 7), ('f', 6)]

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

## EXERCISE TIME!

<ol>
<li>Print the keys of all values that are even
<li>Print the key with the maximum value
<li>Print the sum of all the values
</ol>

```
dictionary = {
    'a': 3, 
    'b': 2, 
    'c': 10, 
    'd': 7, 
    'e': 9, 
    'f' : 12, 
    'g' : 13
    }
```

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

## Back to iris

In [23]:
# iterate over items in iris

for key, val in iris.items():
    print "Key:", key
    print "  Value:", val[:10]

Key: target_names
  Value: ['setosa' 'versicolor' 'virginica']
Key: data
  Value: [[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]]
Key: target
  Value: [0 0 0 0 0 0 0 0 0 0]
Key: DESCR
  Value: Iris Plant
Key: feature_names
  Value: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


## All the values are stored as lists....what are lists?

Lists
====
<ul>
<li>Array of elements
<li>Elements *can be* of different types
<li>Data can be accessed by using indexing and manipulated
<li>Python indexing begins at 0
<li>Lists keep the order of the elements
<li>List of lists
</ul>

Lists (generally) are sequences of the same kind of stuff, and you deal with the items individually.

In [24]:
x = [0,1,2,3,4,5]
print x
print type(x)

[0, 1, 2, 3, 4, 5]
<type 'list'>


In [25]:
x[1:4]

[1, 2, 3]

In [26]:
x[-1] = 10
print x

[0, 1, 2, 3, 4, 10]


In [27]:
x[::2] # every 2nd element

[0, 2, 4]

In [28]:
x[::-1] # reverse

[10, 4, 3, 2, 1, 0]

In [29]:
x + x # append

[0, 1, 2, 3, 4, 10, 0, 1, 2, 3, 4, 10]

In [30]:
x * 3

[0, 1, 2, 3, 4, 10, 0, 1, 2, 3, 4, 10, 0, 1, 2, 3, 4, 10]

In [31]:
x.append(20)   # changes value of x
x

[0, 1, 2, 3, 4, 10, 20]

In [32]:
x.extend([3,4,5])
x

[0, 1, 2, 3, 4, 10, 20, 3, 4, 5]

In [33]:
x.index(20)   # first occurence

6

In [34]:
x.count(3)

2

In [35]:
x = [1,2,[3,4],5,6]

In [36]:
x[1], x[2], x[2][1]

(2, [3, 4], 4)

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

## EXERCISE TIME!

1) Write a program that calculates and returns the euclidean distance between two points `u = (3,0)` and `v = (6,4)`.

Recall the distance formula:
$$
D = \sqrt{(u_{1} - v_{1})^2 + (u_{2} - v_{2})^2}
$$

2) Write a program that returns the greater of the first or last element of a list of integers. <br>

For example: `[1,-2,7,5]` should return `5`.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

## Back to iris

In [39]:
# iterate over items in iris

for key, val in iris.items():
    print "Key:", key
    print "  Value:", val[:10]

Key: target_names
  Value: ['setosa' 'versicolor' 'virginica']
Key: data
  Value: [[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]]
Key: target
  Value: [0 0 0 0 0 0 0 0 0 0]
Key: DESCR
  Value: Iris Plant
Key: feature_names
  Value: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


## Let's summarize the `data`

In [40]:
iris['data'][:10]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1]])

In [41]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

## Find average `sepal length`

In [42]:
sum_ = 0
for val in iris['data']:
    sum_ += val[0]  # sepal length is first element of each row

sum_/len(iris['data'])

5.8433333333333346

## Find largest `petal width`

In [43]:
max_ = 0
for val in iris['data']:
    if max_ < val[2]:
        max_ = val[2]
max_

6.9000000000000004

In [44]:
# can also write it like:

sum([val[0] for val in iris['data']])/len(iris['data'])

5.8433333333333346

In [45]:
max([val[2] for val in iris['data']])

6.9000000000000004

List (and dict) Comprehension and One Liners <a id='compr'></a>
=====

<ul>
<li>Can write entire `for` loop or `if` statement in 1 line if it involves iterating over a list and doing some action
<li>List comprehensions are typical of and very conducive to **functional programming**.
<li>Very slick and can be easier to read. However, easy to get carried away.
<li>Very useful for text analysis
<li>Rule of thumb:
<ul>
<li>List comprehensions are used for creating lists
<li>For loops are better for doing something with the elements of a list
</ul>
</ul>

In [46]:
x = range(1,10)
x

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [47]:
for i in x:
    print i**2,

1 4 9 16 25 36 49 64 81


In [48]:
[i**2 for i in x]

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [49]:
l = []
for i in x:
    if i**.5 == int(i**.5):
        l.append(i)
l[-1]

9

In [50]:
[i for i in x if i**.5==int(i**.5)][-1]

9

In [51]:
[x**2 if x%2 == 0 else x**3 for x in range(10)]

[0, 1, 4, 27, 16, 125, 36, 343, 64, 729]

In [53]:
[v for k, v in dictionary.items() if k == 'a' or k == 'g']

[3, 13]

**But don't go overboard...**

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

## EXERCISE TIME!

1) Create the following matrix using:<br>
<ol>
<li>Nested for loops<br>
<li>List comprehension
</ol>

```
[[1, 0, 0, 0, 0], 
 [0, 2, 0, 0, 0], 
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0],
 [0, 0, 0, 0, 5]]
```

Hint: Think of the matrix as a list of lists. No need to stack the lists on top of each other like above.

2) Write a list comprehension that does the same thing as these nested `for` loops:

```
L = []
for i in range(10):
    for j in {2, 5, 9}:
        if i != j:
            L.append((i,j))
print L
```

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

## Back to iris

In [56]:
petal = [val[0] for val in iris['data']]

In [57]:
type(petal)

list

## Find the index with the largest value of `petal` + `sepal length`

In [58]:
iris.keys()

['target_names', 'data', 'target', 'DESCR', 'feature_names']

In [59]:
iris.feature_names, iris.target_names

(['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 array(['setosa', 'versicolor', 'virginica'], 
       dtype='|S10'))

In [60]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Find the species with the largest average value of `petal length`

In [1]:
iris.keys()    # remind us what keys there are

NameError: name 'iris' is not defined

In [2]:
print iris.feature_names   # petal length is 3rd columns
print iris.target_names   # 3 different species

NameError: name 'iris' is not defined

In [3]:
iris.target    # the first 50 are setosa, second 50 veriscolor, third 50 are virginica

NameError: name 'iris' is not defined

In [61]:
# create dictionary to hold averages
petal_length_dict = dict.fromkeys(iris.target_names, 0)
    
for e, petal in enumerate(iris.data):
    
    if e < 50:
        petal_length_dict[iris.target_names[0]] += petal[2]
    elif e < 100:
        petal_length_dict[iris.target_names[1]] += petal[2]
    else:
        petal_length_dict[iris.target_names[2]] += petal[2]
        
petal_length_dict = { k : v/50 for k, v in petal_length_dict.items()}
petal_length_dict

[[array([ 5.1,  3.5,  1.4,  0.2]), 0],
 [array([ 4.9,  3. ,  1.4,  0.2]), 0],
 [array([ 4.7,  3.2,  1.3,  0.2]), 0],
 [array([ 4.6,  3.1,  1.5,  0.2]), 0],
 [array([ 5. ,  3.6,  1.4,  0.2]), 0],
 [array([ 5.4,  3.9,  1.7,  0.4]), 0],
 [array([ 4.6,  3.4,  1.4,  0.3]), 0],
 [array([ 5. ,  3.4,  1.5,  0.2]), 0],
 [array([ 4.4,  2.9,  1.4,  0.2]), 0],
 [array([ 4.9,  3.1,  1.5,  0.1]), 0],
 [array([ 5.4,  3.7,  1.5,  0.2]), 0],
 [array([ 4.8,  3.4,  1.6,  0.2]), 0],
 [array([ 4.8,  3. ,  1.4,  0.1]), 0],
 [array([ 4.3,  3. ,  1.1,  0.1]), 0],
 [array([ 5.8,  4. ,  1.2,  0.2]), 0],
 [array([ 5.7,  4.4,  1.5,  0.4]), 0],
 [array([ 5.4,  3.9,  1.3,  0.4]), 0],
 [array([ 5.1,  3.5,  1.4,  0.3]), 0],
 [array([ 5.7,  3.8,  1.7,  0.3]), 0],
 [array([ 5.1,  3.8,  1.5,  0.3]), 0],
 [array([ 5.4,  3.4,  1.7,  0.2]), 0],
 [array([ 5.1,  3.7,  1.5,  0.4]), 0],
 [array([ 4.6,  3.6,  1. ,  0.2]), 0],
 [array([ 5.1,  3.3,  1.7,  0.5]), 0],
 [array([ 4.8,  3.4,  1.9,  0.2]), 0],
 [array([ 5. ,  3. ,  1.6

In [ ]:
# For those interested in numpy (next class!)
np.sum(np.split(iris.data.T[2],3),axis=1)/50

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

## EXERCISE TIME!

#### Matrix Multiplication

See <a href='https://www.mathsisfun.com/algebra/matrix-multiplying.html'>here</a> for a refresher.

Create a function `dot_product(A, B)` that multiplies two matrices, $A$ and $B$ and returns their dot product.
<br>

Assume that the dimensions of $A$ and $B$ satisfy matrix multiplication (i.e. their dimensions "work out")

For example, if:
<br>

$A$ = ```[[5,4,3,7], 
    [1,2,3,4]]```
    
(a **2 X 4** matrix) and 
<br>

$B$ = ```[[3,4,5], 
    [-1,6,7], 
    [0,0,1], 
    [9,11,-2]]``` 

(a **4 X 3** matrix) then the output of `dot_product(A,B)` is
<br>

$C$ = ```[[74, 121, 42], 
     [37, 60, 14]]``` 

(a **2 X 3** matrix)

The result, $C$, has a number of rows (**2**), a number of columns (**3**) and some "hidden" value (**4**) which is shared by $A$ and $B$. As a result, this operation requires 3 `for` loops.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Take away
===


<ul>
<li>Load a basic dataset
<li>Explore it, manipulate it
<li>Understand basic data types and control structures (most important are `if` statement and `for` loops)
<li>Write one line list comprehensions - and know when not to.
</ul>

Review Problems<a id='hmwk'></a>
===

**Q1.** 

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000
<ul>
<li>Using a `for` loop
<li>Using list comprehension
</ul>

**Q2.** 

The sum of the squares of the first ten natural numbers is
$$
1^2 + 2^2 + ... + 10^2 = 385
$$
The square of the sum of the first ten natural numbers is
$$
(1 + 2 + ... + 10)^2 = 55^2 = 3025
$$
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.

Write a program to find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum. (Euler problem #6)

The answer should be `25164150`.

**Q3.**

A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

$$
a^2 + b^2 = c^2
$$
For example, $3^2 + 4^2 = 9 + 16 = 25 = 5^2$

There exists **exactly one** Pythagorean triplet for which a + b + c = 1000.
Write a program to find the product abc. (Euler problem #9)

The answer should be `(200, 375, 425, 31875000)`.

**Q4.**

Write a program that prints the numbers from 1 to 100. But for multiples of **three** print “Fizz” instead of the number and for the multiples of **five** print “Buzz”. For numbers which are multiples of both three and five print “FizzBuzz”.

**Q5**.

Given the list:

`names = [ 'CURLY', 'mOE', 'larry', 'M', 'LaRrY', 'curly']`

Write a program that produces the set:

`['Moe', 'Larry', 'Curly']`

Use list comprehension.


**Q6**.
<br>

Write a list comprehension to flatten a list of sublists. For example:
<br>

`[[1,2,3],[4,5],[6,7,8,9]]` becomes `[1,2,3,4,5,6,7,8,9]`


**Q7.**
<br>

Without looping, find the State with the smallest city population. Hint: It's NC :) Also, look up the `get` function.
```
states = {
    "CA" : 'SFO',
    "NY" : 'NYC',
    'NC' : 'DUR'
}

cities = {
    'SFO': 1000,
    'NYC': 1500,
    'DUR': 500
}
```

## Bonus (Hard!) Questions

A palindromic number reads the same both ways. The largest palindrome made from the product of **two 2-digit** numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of **two 3-digit** numbers.