Introduction to Python for Data Science
===

# WHOAREWE?

<ul>
<li>Ilan, Ai, Squarespace, Duke
<li>TAs: Paul and Nick, Ai
</ul>

# WHOAREYOU?

<ul>
<li>Name
<li>Coding experience
<li>Why are you here
<li>Something interesting | Favoriate band | restaurant (in Durham) | hometown (if not Durham)
</ul>

# AGENDA

0. [Overview](#overview)
1. [Review](#review)
2. [Iris Data](#iris)
3. [Dictionary, list](#dict)
4. [List comprehension](#compr)
5. [Probability refresher](#prob)
6. [Review Problems](#hmwk)

# What you can expect to become an expert in after this class:

<img src='../images/data_science_traits.png'>

# Or not.....

# COURSE OVERVIEW <a id='overview'></a>

<ul>
<li>Will be using notebooks to review concepts
<ul>
<li>Ask questions
<li>**Don't worry about memorizing or understanding everything the first time** - takes a while to sink in
<li>Do the in class exercises - collaborate!
</ul>
<li>Try the at home exercises - don't be discouraged if they take a while or you don't get it right away
<ul>
<li>Feel free to email me with questions
<li>If you want more - let me know and I'll provide more!
</ul>
<li>Syllabus is tentative - based on class flow
<li>**Google is my best friend**. Consider making it yours.
</ul>

### Jupyter

<ul>
<li>Interative notebook
<ul>
<li>Write code in cells and run to see output. Cells communicate - values are carried forward.
<li>Can also insert markdown or $\LaTeX$, i.e. $y = \beta_0 + \beta_1 x + \beta_2x^2$
<li>Can also insert images, etc..
</ul>
<li>Makes for easy prototyping
<li>Quick visualizations
<li>Shareable, live code
<li><a href="https://ipython.org/">IPython</a> is the Python *kernel* for Jupyter - but there is a Ruby kernel, Julia, ...
<li>...but can promote bad code practice, not used for production
<li>Spend time getting to know the notebook. Shortcuts, etc...
</ul>

Review pre work <a id='review'></a>
======

<ul>
<li>Variables
<li>Boolean logic
<li>Operators
<li>`if` statement
<li>Built-in functions
</ul>

**Q1**.
<br>

Without using Python, what's the following output?

<ol>
<li>`not (1 == 1 and 0 != 1)`
<li>`3 == 3 and (not ("testing" == "testing" or "Python" == "Fun"))`
<li>`20 == ((20 % 3) ** 2 + 1) * (9//2)`
</ol>


In [ ]:
## SOLUTION

False
False
True

**Q2**.
<br>

For the following string, replace every occurrence of the first character with #, except for the first character. So:

`'this is a sentence that starts with the letter t'`

Becomes

`'this is a sen#ence #ha# s#ar#s wi#h #he le##er #'`


In [1]:
## SOLUTION

s = 'this is a sentence that starts with the letter t'
char = s[0]  
s = s.replace(char, '#')  
s = char + s[1:] 
s

'this is a sen#ence #ha# s#ar#s wi#h #he le##er #'

**Q3**.

Write a program that prints, to the console, a list of 2 integers and 1 string. Do this:

<ol>
<li>Using the `format` function
<li>Not using `format`
</ol>

For example:

`[2,'s',4]`

Each of the three elements should be a variable, not hardcoded. Make sure the spacing is as shown above.

In [2]:
## SOLUTION

a = 2
b = 's'
c = 4

print "Using format:", "    [{},{},{}]".format(a,b,c)
print "Not using format:", "[" + str(a) + "," + str(b) + "," + str(c) + "]" 

Using format:     [2,s,4]
Not using format: [2,s,4]


**Q4**.
<br>

Write a function `power_floor(a,b)` that returns the floor of `a` to the power of `b`. "Floor" means "rounded down". i.e. `power_floor(5.5,3)` outputs `166`. 

In [3]:
## SOLUTION

def power(a,b):
#    return round(a**b,0)
    return int(a**b)

power(5.5,3)

166

# IRIS DATASET<a id='iris'></a> - Running example

### Classifying types of planet species (target) based on measurements (features).

Click <a href='https://en.wikipedia.org/wiki/Iris_flower_data_set'>here</a> for more info.

<img src='../images/iris_petal_sepal.png'>

In [10]:
from sklearn import datasets    # sklearn is great (more later!)
iris = datasets.load_iris()     # load the dataset

In [11]:
print iris

{'target_names': array(['setosa', 'versicolor', 'virginica'], 
      dtype='|S10'), 'data': array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.

## How can we see the data?

In [13]:
iris.keys()

['target_names', 'data', 'target', 'DESCR', 'feature_names']

In [14]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
iris.data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [16]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

## What is this object?

In [16]:
type(iris)

sklearn.datasets.base.Bunch

Dictionary<a id='dict'></a>
----
<ul>
<li>Consist of pairs of keys and their corresponding values. Like a dictionary, lookup the `key` to get some `value`
<li>Values aren't numbered or in any specific order. Key's are also not ordered.
<li>You can add, remove, and modify the values in dictionaries
<li>Looks like a `JSON` object
</ul>

In [23]:
# how to initialize a dictionary

dictionary = {'a': 1, 'b':2, 'c':3}
print dictionary

{'a': 1, 'c': 3, 'b': 2}


In [25]:
dictionary['b']

2

In [14]:
dictionary1 = dict(d = 4, e = 5, f = 6)
dictionary1

{'d': 4, 'e': 5, 'f': 6}

In [15]:
# appending elements

dictionary.update(dictionary1)
dictionary

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}

In [22]:
dictionary.keys()

['a', 'c', 'b', 'e', 'd', 'f']

In [23]:
dictionary.values()

[1, 3, 2, 5, 4, 6]

In [24]:
dictionary['g'] = 7
dictionary

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7}

In [16]:
# iterating through a dictionary

for key in dictionary:
    print key, dictionary[key]

a 1
c 3
b 2
e 5
d 4
f 6


In [17]:
for key, value in dictionary.items():
    print key, value

a 1
c 3
b 2
e 5
d 4
f 6


In [18]:
dictionary.items()   # list of tuples

[('a', 1), ('c', 3), ('b', 2), ('e', 5), ('d', 4), ('f', 6)]

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

## EXERCISE TIME!

<ol>
<li>Print the keys of all values that are even
<li>Print the key with the maximum value
<li>Print the sum of all the values
</ol>

```
dictionary = {
    'a': 3, 
    'b': 2, 
    'c': 10, 
    'd': 7, 
    'e': 9, 
    'f' : 12, 
    'g' : 13
    }
```

In [20]:
dictionary = {
    'a': 3, 
    'b': 2, 
    'c': 10, 
    'd': 7, 
    'e': 9, 
    'f' : 12, 
    'g' : 13
    }
dictionary

{'a': 3, 'b': 2, 'c': 10, 'd': 7, 'e': 9, 'f': 12, 'g': 13}

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

In [ ]:
## SOLUTION - 1

dictionary = {'a': 3 , 'b': 2, 'c': 10, 'd': 7, 'e': 9, 'f' : 12, 'g' : 13}

for key, val in dictionary.items():
    if val % 2 == 0:
        print key

print
## SOLUTION - 2, 3

max_, sum_, key_ = 0, 0, 0

for key, val in dictionary.items():
    sum_ += val
    if max_ < val:
        key_, max_ = key, val

print "Sum: ", sum_
print "Max: ", key_

## Back to iris

In [28]:
# iterate over items in iris

for key, val in iris.items():
    print "Key:", key
    print "  Value:", val[:10]  # just the first 10 values

Key: target_names
  Value: ['setosa' 'versicolor' 'virginica']
Key: data
  Value: [[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]]
Key: target
  Value: [0 0 0 0 0 0 0 0 0 0]
Key: DESCR
  Value: Iris Plant
Key: feature_names
  Value: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


## All the values are stored as lists....what are lists?

Lists
====
<ul>
<li>Array of elements
<li>Elements *can be* of different types
<li>Data can be accessed by using indexing and manipulated
<li>Python indexing begins at 0
<li>Lists keep the order of the elements
<li>List of lists
</ul>

Lists (generally) are sequences of the same kind of stuff, and you deal with the items individually.

In [26]:
x = [0,1,2,3,4,5]
print x
print type(x)

[0, 1, 2, 3, 4, 5]
<type 'list'>


In [27]:
x[1:4]

[1, 2, 3]

In [28]:
x[-1] = 10
print x

[0, 1, 2, 3, 4, 10]


In [32]:
x[::2] # every 2nd element

[0, 2, 4]

In [33]:
x[::-1] # reverse - pretty handy

[10, 4, 3, 2, 1, 0]

In [34]:
x + x # append

[0, 1, 2, 3, 4, 10, 0, 1, 2, 3, 4, 10]

In [32]:
x+[20]
print x

[0, 1, 2, 3, 4, 10]


In [33]:
x.append(20)   # changes value of x
x

[0, 1, 2, 3, 4, 10, 20]

In [37]:
x.extend([3,4,5])
x

[0, 1, 2, 3, 4, 10, 20, 3, 4, 5]

In [38]:
x.index(20)   # first occurence

6

In [39]:
x.count(3)

2

In [40]:
x = [1,2,[3,4],5,6]  # list of lists

In [41]:
x[1], x[2], x[2][1]

(2, [3, 4], 4)

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

## EXERCISE TIME!

1) Write a program that calculates and returns the euclidean distance between two points in 3-dimensions `u = (3,0,1)` and `v = (6,4,-1)`.

Recall the distance formula:
$$
D = \sqrt{(u_{1} - v_{1})^2 + (u_{2} - v_{2})^2 + (u_{3} - v_{3})^2}
$$

2) Write a program that returns the greater of the first or last element of a list of integers. <br>

For example: `[1,-2,7,9,5]` should return `5`.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

In [1]:
## SOLUTION - 1
u = [3,0,1]
v = [6,4,-1]

(((v[0] - u[0])**2 + (v[1] - u[1])**2 + (v[2] - u[2])**2))**0.5

5.385164807134504

In [2]:
## SOLUTION - 2

u = [1,-2,7,9,5]
max(u[0], u[-1])

5

## Back to iris

In [42]:
# iterate over items in iris

for key, val in iris.items():
    print "Key:", key
    print "  Value:", val[:10]

Key: target_names
  Value: ['setosa' 'versicolor' 'virginica']
Key: data
  Value: [[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]]
Key: target
  Value: [0 0 0 0 0 0 0 0 0 0]
Key: DESCR
  Value: Iris Plant
Key: feature_names
  Value: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


## Let's summarize the `data`

In [43]:
iris['data'][:10]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1]])

In [44]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

## Find average `sepal length`

In [38]:
sum_ = 0
idx = iris.feature_names.index('sepal length (cm)')  # used to find the correct column

for val in iris['data']:
    sum_ += val[idx]  # return the index where the condition is met

sum_/len(iris['data'])

5.8433333333333346

## Find largest `petal width`

In [69]:
max_ = 0
idx = iris.feature_names.index('petal width (cm)')

for val in iris['data']:
    if max_ < val[idx]:
        max_ = val[idx]
max_

2.5

In [65]:
# can also write it like:
idx = iris.feature_names.index('sepal length (cm)')

sum([val[idx] for val in iris['data']])/len(iris['data'])

5.8433333333333346

In [70]:
idx = iris.feature_names.index('petal width (cm)')
max([val[idx] for val in iris['data']])

2.5

List (and dict) Comprehension and One Liners <a id='compr'></a>
=====

<ul>
<li>Can write entire `for` loop or `if` statement in 1 line if it involves iterating over a list and doing some action
<li>List comprehensions are typical of and very conducive to **functional programming**.
<li>Very slick and can be easier to read. However, easy to get carried away.
<li>Very useful for text analysis
<li>Rule of thumb:
<ul>
<li>List comprehensions are used for creating list objects for later use
<li>For loops are better for doing something with the elements of a list - i.e. iterating over a list
</ul>
</ul>

In [39]:
x = range(1,10)
x

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
y=[]
for i in x:
    y.append(i**2),

1 4 9 16 25 36 49 64 81


In [25]:
y = [i**2 for i in x]

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [43]:
# find perfect squares

l = []
for i in x:
    if i**.5 == int(i**.5):
        l.append(i)
l

[1, 4, 9]

In [30]:
[i for i in x if i**.5==int(i**.5)]

[1, 4, 9]

In [31]:
[x**2 if x%2 == 0 else x**3 for x in range(10)]

[0, 1, 4, 27, 16, 125, 36, 343, 64, 729]

In [44]:
dictionary

{'a': 1, 'b': 2, 'c': 3}

In [32]:
[v for k, v in dictionary.items() if k == 'a' or k == 'g']

[1]

**But don't go overboard...**

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

## EXERCISE TIME!

1) Create the following matrix using:<br>
<ol>
<li>Nested for loops<br>
<li>List comprehension
</ol>

```python
[[1, 0, 0, 0, 0], 
 [0, 2, 0, 0, 0], 
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0],
 [0, 0, 0, 0, 5]]
```

Hint: Think of the matrix as a list of lists. No need to stack the lists on top of each other like above.

2) Write a list comprehension that does the same thing as these nested `for` loops:

```python
L = []
for i in range(10):
    for j in {2, 5, 9}:
        if i != j:
            L.append((i,j))
print L
```

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

In [3]:
## SOLUTION - 1

matrix = []
for i in range(5):
    row = []
    for j in range(5):
        if i == j:
            row.append(i+1)
        else:
            row.append(0)
    matrix.append(row)

        
print matrix
print [[item_idx+1 if item_idx == row_idx else 0 for item_idx in range(0, 5) ] for row_idx in range(0, 5) ]

[[1, 0, 0, 0, 0], [0, 2, 0, 0, 0], [0, 0, 3, 0, 0], [0, 0, 0, 4, 0], [0, 0, 0, 0, 5]]
[[1, 0, 0, 0, 0], [0, 2, 0, 0, 0], [0, 0, 3, 0, 0], [0, 0, 0, 4, 0], [0, 0, 0, 0, 5]]


In [4]:
## SOLUTION - 2

print [(i,j) for i in range(10) for j in {2,5,9} if i != j]

[(0, 9), (0, 2), (0, 5), (1, 9), (1, 2), (1, 5), (2, 9), (2, 5), (3, 9), (3, 2), (3, 5), (4, 9), (4, 2), (4, 5), (5, 9), (5, 2), (6, 9), (6, 2), (6, 5), (7, 9), (7, 2), (7, 5), (8, 9), (8, 2), (8, 5), (9, 2), (9, 5)]


# Probability refresher<a id='prob'></a>

<img src='../images/Conditional-Probability.png'>

### Basic Probability

<ul>
<li>Things in nature occur according to random processes. 
<li>We say event $X$, is generated by some probability distribution, $p(x)$.
<ul>
<li>Random process: rolling a die
<li>Space of possible outcomes: $\{1,2,3,4,5,6\}$
<li>Event: $X$ is the event that we roll a 3. 
<li>Want: $p(3) = P(X=3)$ = ? (assume each outcome is equally likely)
</ul>
<li>Probabilities are bounded between 0 and 1. $0 \le P(X) \le 1$
<li>The sum of the probabilities in the set of possible events, is 1.0. $\sum p(x) = 1.0$
<li>Probabilities can be discrete (i.e. flipping a coin, number of fish in a pond) or continuous (i.e. average height, time between train arrivals). **Can you think of another example of discrete or continuous probabilities?**
</ul>

### Important measures

<ul>
<li>A data point is refered to as $x_i$ or $X_i$. Technically $X_i$ is a random variable.
<li>Expected Value (aka the mean):
$$
\mu = E[X] = \sum_{i=1}^n x_i p(x_i)
$$
<li>Variance:
$$
\sigma^2 = Var(X) = E(X - \mu)^2 = E[X^2] - E[X]^2 = \sum_{i=1}^n p(x_i)(x_i - \mu)^2
$$
</ul>

### Basic Set Theory

<ul>
<li>In general, for any two events $A$ and $B$<br>
 - $P(A \cup B) = P(A) + P(B) - P(A \cap B)$
<li>If $A$ and $B$ are **mutually exclusive** events (i.e. $A$ = rain tomorrow, $B$ = doesn't rain tomorrow)<br>
 - $P(A \cup B) = P(A) + P(B)$
<li>If $A$ and $B$ are **independent** events (i.e. $A$ = rain tomorrow, $B$ = flip a heads)<br>
 - $P(A \cap B) = P(A) \times P(B)$
<li>**Conditional probability**. We write the probability of observing $A$ given $B$ occured<br>
 - $P(A|B) = \dfrac{P(A \cap B)}{P(B)}$
<li>**Bayes rule**. We write the probability of $A$ given $B$<br>
 - $P(A|B) = \dfrac{P(B|A)P(A)}{P(B)}$
</ul>


<img src='../images/probability-stat-cartoon.jpg'>

In [48]:
import math

ways = len('possibility')
math.factorial(ways)

39916800

In [5]:
# dice rolling experiment: roll a dice. What's the expected value of the roll? What's the variance?

sides = range(1,7)  # X_i's {1,2,3,4,5,6}
probs = 1/6.       # p(x) - they are all 1/6
expected_value = [i*probs for i in sides]
print sum(expected_value)

3.5


In [6]:
variance = sum([(i - sum(expected_value))**2 for i in sides])/len(sides)
print variance

2.91666666667


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

## EXERCISE TIME!

Dice rolling experiment: Roll **two** dice. Record the sum of the sides. <br>

1) What's the expected value of the roll? <br>
2) What's the variance?<br>
3) What's the probability that one of the dice is a `3`, given the sum is `7`?<br>
4) What do you notice about the results of 1) and 2)?


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

In [5]:
## SOLUTION

from __future__ import division

sides = range(2,13)  # X_i's = {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
probs = [1,2,3,4,5,6,5,4,3,2,1] # p(x) = {1/36, 2/36, 3/36, 4/36, 5/36, 6/36, 5/36, 4/36, 3/36, 2/36, 1/36}

expected_value = sum([i[0]*i[1]/36 for i in zip(probs,sides)])
print expected_value

variance = sum([i[0]**2*i[1]/36 for i in zip(sides,probs)]) - expected_value**2

print variance

variance2 = sum([j[0]*j[1]/36 for j in zip(probs,[(i-expected_value)**2 for i in sides])])

print variance2

# P(one dice = 3 | total = 7) = P(one dice = 3 AND total = 7)/P(total = 7)
# (3,4) - 1/36
# (4,3) - 1/36
# (1,6) (2,5) (3,4) (4,3) (5,2) (6,1) - 6/36

conditional_prob = (2/36)/(6/36)
print conditional_prob


7.0
5.83333333333
5.83333333333
0.333333333333


## Back to iris

In [84]:
petal = [val[0] for val in iris['data']]
petal[:10]

[5.0999999999999996,
 4.9000000000000004,
 4.7000000000000002,
 4.5999999999999996,
 5.0,
 5.4000000000000004,
 4.5999999999999996,
 5.0,
 4.4000000000000004,
 4.9000000000000004]

## Find the species with the largest average value of `petal length`

In [87]:
print iris.keys()    # remind us what keys there are

['target_names', 'data', 'target', 'DESCR', 'feature_names']


In [86]:
print iris.feature_names   # petal length is 3rd columns
print iris.target_names   # 3 different species

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [88]:
print iris.target    # the first 50 are setosa, second 50 veriscolor, third 50 are virginica

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [49]:
dict.fromkeys(iris.target_names, 0)

{'setosa': 0, 'versicolor': 0, 'virginica': 0}

In [52]:
# create dictionary to hold averages
petal_length_dict = dict.fromkeys(iris.target_names, 0)
    
for e, petal in enumerate(iris.data):
    
    if e < 50:
        petal_length_dict[iris.target_names[0]] += petal[2]
    elif e < 100:
        petal_length_dict[iris.target_names[1]] += petal[2]
    else:
        petal_length_dict[iris.target_names[2]] += petal[2]
        
petal_length_dict = { k : v/50 for k, v in petal_length_dict.items()}
print petal_length_dict

{'setosa': 1.464, 'versicolor': 4.2599999999999998, 'virginica': 5.5519999999999996}


In [91]:
# For those interested in numpy (next class!)
print np.sum(np.split(iris.data.T[2],3),axis=1)/50

[ 1.464  4.26   5.552]


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

<img src='../images/matrix_multiplication.png'>

## EXERCISE TIME!

#### Matrix Multiplication

See <a href='https://www.mathsisfun.com/algebra/matrix-multiplying.html'>here</a> for a brief review.

Create a function `dot_product(A, B)` that multiplies two matrices, $A$ and $B$ and returns their dot product. Assume that the dimensions of $A$ and $B$ satisfy matrix multiplication (i.e. their dimensions "work out"). 

For example, if:
<br>

$A$ = ```[[5,4,3,7], 
    [1,2,3,4]]```
    
(a **2 X 4** matrix) and 
<br>

$B$ = ```[[3,4,5], 
    [-1,6,7], 
    [0,0,1], 
    [9,11,-2]]``` 

(a **4 X 3** matrix) then the output of `dot_product(A,B)` is
<br>

$C$ = ```[[74, 121, 42], 
     [37, 60, 14]]``` 

(a **2 X 3** matrix)

The result, $C$, has a number of rows (**2**), a number of columns (**3**) and some "hidden" value (**4**) which is shared by $A$ and $B$. As a result, this operation requires 3 `for` loops.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

In [ ]:
## SOLUTION

def dot_product(A,B):
    
    rows = len(A)
    shared = len(B)
    cols = len(B[0])
    
    C = rows*[0]   # initialize C to be a list of length = to rows of A
    
    for i in range(rows):  # iterate over rows of A, i.e. (0, 1)
        C[i] = cols*[0]    # set each row of C to be a list of length = columns of B
        
        for k in range(cols):  # iterate over the columns of B, i.e. (0, 1, 2)
            
            for j in range(shared):  # iterate over the "shared" dimension of A and B, i.e. (0, 1, 2, 3) (columns of A and rows of B)
                
                C[i][k] += A[i][j]*B[j][k]
            
    return C

A = [[5,4,3,7],[1,2,3,4]]
B = [[3,4,5],[-1,6,7],[0,0,1],[9,11,-2]]
dot_product(A,B)

Take away
===


<ul>
<li>Load a basic dataset
<li>Explore it, manipulate it
<li>Understand basic data types and control structures (most important are `if` statement and `for` loops)
<li>Write one line list comprehensions - and know when not to.
<li>Basic probability
<li>Matrix multiplication - the hard way
</ul>

At Home Review Problems<a id='hmwk'></a>
===

**Q1.** 

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000
<ul>
<li>Using a `for` loop
<li>Using list comprehension
</ul>

In [1]:
## SOLUTION
sum([i for i in list(range(1,1000)) if i % 3 == 0 or i % 5 == 0])

233168

**Q2.** 

The sum of the squares of the first ten natural numbers is
$$
1^2 + 2^2 + ... + 10^2 = 385
$$
The square of the sum of the first ten natural numbers is
$$
(1 + 2 + ... + 10)^2 = 55^2 = 3025
$$
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.

Write a program to find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum. (Euler problem #6)

The answer should be `25164150`.

In [2]:
## SOLUTION
sum(range(1,101))**2 - sum([i**2 for i in range(1,101)])

25164150

**Q3.**

A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

$$
a^2 + b^2 = c^2
$$
For example, $3^2 + 4^2 = 9 + 16 = 25 = 5^2$

There exists **exactly one** Pythagorean triplet for which a + b + c = 1000.
Write a program to find the product abc. (Euler problem #9)

The answer should be `(200, 375, 425, 31875000)`.

In [3]:
## SOLUTION
for a in range(1000):
    for b in range(a+1,1000):
        for c in range(b+1, 1000):
            if a + b + c == 1000 and a**2 + b**2 == c**2:
                print (a, b, c, a*b*c)

(200, 375, 425, 31875000)


**Q4.**

Write a program that prints the numbers from 1 to 100. But for multiples of **three** print “Fizz” instead of the number and for the multiples of **five** print “Buzz”. For numbers which are multiples of both three and five print “FizzBuzz”.

In [4]:
## SOLUTION
for i in range(1, 101):
    if i % 15 == 0:
        print("FizzBuzz"),
    elif i % 3 == 0:
        print("Fizz"),
    elif i % 5 == 0:
        print("Buzz"),
    else:
        print(i),

1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz 16 17 Fizz 19 Buzz Fizz 22 23 Fizz Buzz 26 Fizz 28 29 FizzBuzz 31 32 Fizz 34 Buzz Fizz 37 38 Fizz Buzz 41 Fizz 43 44 FizzBuzz 46 47 Fizz 49 Buzz Fizz 52 53 Fizz Buzz 56 Fizz 58 59 FizzBuzz 61 62 Fizz 64 Buzz Fizz 67 68 Fizz Buzz 71 Fizz 73 74 FizzBuzz 76 77 Fizz 79 Buzz Fizz 82 83 Fizz Buzz 86 Fizz 88 89 FizzBuzz 91 92 Fizz 94 Buzz Fizz 97 98 Fizz Buzz


**Q5**.

Given the list:

`names = [ 'CURLY', 'mOE', 'larry', 'M', 'LaRrY', 'curly']`

Write a program that produces the set:

`['Moe', 'Larry', 'Curly']`

Use list comprehension.


In [5]:
## SOLUTION

names = [ 'CURLY', 'mOE', 'larry', 'M', 'LaRrY', 'curly']

sorted({ name[0].upper() + name[1:].lower() for name in names if len(name) > 1 }, key=len)

['Moe', 'Larry', 'Curly']

**Q6**.
<br>

Write a list comprehension to flatten a list of sublists. For example:
<br>

`[[1,2,3],[4,5],[6,7,8,9]]` becomes `[1,2,3,4,5,6,7,8,9]`


In [6]:
## SOLUTION

biglist = [[1,2,3],[4,5],[6,7,8,9]] 
[element for sublist in biglist for element in sublist]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

**Q7.**
<br>

Without looping, find the State with the smallest city population. Hint: It's NC :) Also, look up the `get` function.
```
states = {
    "CA" : 'SFO',
    "NY" : 'NYC',
    'NC' : 'DUR'
}

cities = {
    'SFO': 1000,
    'NYC': 1500,
    'DUR': 500
}
```

In [7]:
## SOLUTION

states = {
    "CA" : 'SFO',
    "NY" : 'NYC',
    'NC' : 'DUR'
}

cities = {
    'SFO': 1000,
    'NYC': 1500,
    'DUR': 500
}
max_city = max(cities, key = cities.get)
states.keys()[states.values().index(max_city)]

'NY'

**Q8**. Dice rolling.

You have two dice, `A` and `B`. Each of them is a regular `6` sided die. 

1) What's the probability that `A`'s side facing up is greater than `B`'s side facing up.<br>
2) What's the probability that, given `B` is a `2`, that `A` is an odd number.

In [8]:
## SOLUTION

## Bonus (Hard!) Questions

A palindromic number reads the same both ways. The largest palindrome made from the product of **two 2-digit** numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of **two 3-digit** numbers.

In [9]:
## SOLUTION
def is_palindrome(n):
    ''' Checks if n is a palindrome - converts number to string and checks for reverse equality '''
    return str(n) == str(n)[::-1]
    
max_pal = 0
digit_1, digit2 = 0, 0
for i in range(1,1000):
    for j in range(1,1000):
        current_num = i*j
        if is_palindrome(current_num) and current_num > max_pal:
            digit_1, digit_2 = i, j
            max_pal = current_num
            
print max_pal, "=", digit_1, "x", digit_2

906609 = 913 x 993
